{
  "backend": {
    "name": "git-gateway",
    "branch": "master"
  },
  "media_folder": "src/static/img",
  "public_folder": "/static/img",
  "local_backend": true,
  "show_preview_links": false,
  "collections": [
    {
      "label": "Digital Signage",
      "name": "digitalSignage",
      "create": false,
      "extension": "json",
      "files": [
        {
          "label": "-1 Screen",
          "name": "minusOneScreen",
          "file": "src/_data/minus1screen.json",
          "fields": [
            {
              "label": "Key Contacts",
              "name": "keyContacts",
              "widget": "list",
              "collapsed": false,
              "fields": [
                { "label": "Incident Control Officer", "name": "name", "widget": "string" },
                { "label": "Extension", "name": "extension", "widget": "string" },
                { "label": "Radio", "name": "radio", "widget": "string" },
                { "label": "Office Level", "name": "office", "widget": "string" }
              ]
            },
            {
              "label": "First Aiders",
              "name": "firstAiders",
              "widget": "list",
              "collapsed": false,
              "fields": [
                { "label": "First Aider", "name": "name", "widget": "string" },
                { "label": "Extension", "name": "extension", "widget": "string" },
                { "label": "Radio", "name": "radio", "widget": "string" },
                { "label": "Office", "name": "office", "widget": "string" }
              ]
            } 
          ]
        }
      ]  
    }
  ]
}