{
  "backend": {
    "name": "git-gateway",
    "branch": "master"
  },
  "media_folder": "src/static/img",
  "public_folder": "/static/img",
  "local_backend": true,
  "show_preview_links": false,
  "collections": [
    {
      "label": "-1 Screen",
      "name": "minus1Screen",
      "folder": "src/digital-signage",
      "create": true,
      "extension": "json",
      "fields": [
        {
          "label": "Title",
          "name": "title",
          "widget": "hidden",
          "default": "-1 Screen"
        },
        {
          "label": "Key Contacts",
          "name": "keyContacts",
          "widget": "list",
          "field": {
            "label": "Contact",
            "name": "contact",
            "widget": "object",
            "fields": [
              { "label": "Incident Control Officer", "name": "name", "widget": "string" },
              { "label": "Extension", "name": "extension", "widget": "string" },
              { "label": "Radio", "name": "radio", "widget": "string" },
              { "label": "Office Level", "name": "office", "widget": "string" }
            ]
          }
        },
        {
          "label": "First Aiders",
          "name": "firstAiders",
          "widget": "list",
          "field": {
            "label": "First Aider",
            "name": "firstAider",
            "widget": "object",
            "fields": [
              { "label": "First Aider", "name": "name", "widget": "string" },
              { "label": "Extension", "name": "extension", "widget": "string" },
              { "label": "Radio", "name": "radio", "widget": "string" },
              { "label": "Office", "name": "office", "widget": "string" }
            ]
          }
        } 
      ]  
    }
  ]
}